config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'team', to: 'pages#team'
  root to: 'pages#home'
  resources :offers, only: [:index, :show] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :new, :destroy]
  resources :notifications, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
  has_many :notifications, dependent: :destroy
  STATUS = ["pending", "confirmed", "declined"]
  validates :status, inclusion: { in: STATUS }
  validates :booking_date, presence: true

  after_commit :change_status_fake, on: [:create]

  # adjust booking status after time
  def change_status_fake
    Thread.new do
      sleep(5)
      booking = Booking.find(id)
      i = rand(1..2)
      booking.status = STATUS[i]
      booking.save

      # create notification
      fn = booking.offer.user.first_name
      msg = "#{fn} confirmed your booking! Get ready :)" if i == 1
      msg = "#{fn} declined your booking! Next time :(" if i == 2
      Notification.create(booking: booking, user: booking.user, msg: msg)
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  has_and_belongs_to_many :skills, join_table: "offers_skills"

  validates :title, :description, presence: true
  validates :description, length: { minimum: 5, maximum: 250 }

  include PgSearch::Model
  multisearchable against: [:title, :description]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :offer
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :offers, join_table: "offers_skills"
  validates :name, :hue_code, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :offers
  has_many :bookings

  ROLES = ["user", "techy"]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, :user_name, :role, presence: true
  validates :email, uniqueness: true
  validates :role, inclusion: { in: ROLES }
  validates :user_name, length: { minimum: 5, maximum: 20 }

  include PgSearch::Model
  multisearchable against: [:first_name, :last_name]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name, :role])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user:current_user)
  end

  def create
    @booking = Booking.new(set_booking_params)
    offer = Offer.find(params[:offer_id])
    @booking.offer = offer
    @booking.user = current_user
    @booking.status = "pending"
    if @booking.save
      redirect_to bookings_path
    else
      redirect_to offer_path(offer)
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end
  private
  def set_booking_params
    params.require(:booking).permit(:booking_date)
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    # retrieve not showed notifications
    @notifications = Notification.where(user: current_user, showed: false)
    # set showed true
    @notifications.each do |noti|
      noti.showed = true
      noti.save
    end
    # return json
    render json: @notifications
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show]

  def index
    @skills = Skill.all.select { |skill| skill.offers.size > 0 }
    @selected_skills = params[:skills]
    @search = params[:query]
    @available = params[:availablenow] == 'on'
    @offers = Offer.all
    search_offers_by_search_query(@search) if @search.present?
    filter_offers_by_skills(@offers, @selected_skills) if @selected_skills.present?
    filter_by_availablity(@offers) if @available
    @offers
  end

  def show
    @offer = Offer.find(params[:id])
    @booking = Booking.new
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def search_offers_by_search_query(query)
    PgSearch::Multisearch.rebuild(Offer)
    PgSearch::Multisearch.rebuild(User)
    @search_query = PgSearch.multisearch(query)
    # MAKE THE SEARCH FOR THE USER
    @users_results = @search_query.map do |result|
      result.searchable_id if result.searchable_type == 'User'
    end
    # MAKE THE SEARCH FOR THE OFFER
    @offer_results = @search_query.map do |result|
      result.searchable_id if result.searchable_type == 'Offer'
    end
  end

  def filter_offers_by_skills(offers, selected_skills)
    @offers = offers.reject do |offer|
      available_skills = offer.skills.select do |skill|
        selected_skills.include? skill.name
      end
      available_skills.empty?
    end
  end

  def filter_by_availablity(offers)
    @offers = offers.select { |offer| offer.available_now }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def team

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="bookings-container">

  <h1 class="text-xl text-bold text-center">My bookings</h1>

  <div class="flex flex-row flex-wrap justify-center ">
    <% @bookings.each do |booking| %>
      <div class="bookings-card flex flex-col items-center">
        <%= render 'components/offer_card', offer: booking.offer %>
        <div class="flex flex-row justify-even mb-2">
          <div class="date px-2 text-bold text-l"><%= booking.booking_date.strftime("%d.%m.%Y")%></div>
          <div class="status px-2 text-l"><%= booking.status %></div>
        </div>
        <% unless booking.status == 'declined' %>
          <div class="flex flex-row justfiy-between">
            <%= link_to "Cancel", booking_path(booking.id), method: :delete, data: { confirm: "Are you sure?" }, class: "button button-danger" %>
          </div>
        <% end %>
        <% if booking.status == 'declined' %>
          <div class="flex flex-row justfiy-between">
            <%= link_to "Delete", booking_path(booking.id), method: :delete, data: { confirm: "Are you sure?" }, class: "button button-danger" %>
          </div>
        <% end %>
      </div>
      <!-- Status: <%= booking.status %> || <%= link_to "Cancel booking", booking_path(booking.id), method: :delete, data: { confirm: "Are you sure?" } %> -->
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentATechy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body class="flex flex-col">
    <div id="notifications_con"></div>
    <header> <%= render 'components/navbar', user: current_user %></header>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'components/footer' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/offers/index.html.erb
<div class="offers-container flex flex-col items-center">
  <h1 class="text-xl text-bold">Browse offers</h1>
  <%= form_tag offers_path, method: :get do %>
    <div class="flex flex-row items-center justify-center">
        <div class="offers-search-container">
          <%= text_field_tag :query,
            params[:query],
            class: "offers-search-input p-2 m-2 text-l",
            placeholder: "Search names, offers..."
          %>
        </div>
        <%= submit_tag "Find my techy", class: "button button-primary m-1 px-4 py-3" %>
    </div>
    <div class="flex flex-col items-center">
      <input type="checkbox"  id="availablenow" class="tagselect" name="availablenow"/>
      <label for="availablenow" class="hover pill grayscale py-1 text-s px-2 m-1 rounded-pill shadow-xs text-bold" style="background-color: hsl(100, 100%, 90%); color: hsl(100, 100%, 40%)">
          available now
      </label>
    </div>

    <div class="tag-selector flex flex-row flex-wrap items-center justify-center">
      <% @skills.each do |skill| %>

        <input type="checkbox"  id="<%= skill.name %>select" class="tagselect" name="skills[]" value="<%= skill.name %>"/>
        <label for="<%= skill.name %>select" class="hover pill py-1 px-2 m-1 rounded-pill shadow-xs text-xs text-bold" style="background-color: hsl(<%= skill.hue_code %>, 100%, 90%); color: hsl(<%= skill.hue_code %>, 100%, 40%)">
            <%= skill.name %>
        </label>
      <% end %>
    </div>
  <% end %>
  <div class="offers-grid flex flex-row wrap justify-center content-start">
    <%  if @search && !@search.blank? %>
      <% @offers.each do |offer| %>

       <!-- USER RESULTS  -->
        <% if @users_results %>
          <% if offer.user_id.in? @users_results %>
            <%= render 'components/offer_card', offer: offer %>
          <% end %>
        <% end %>

        <!-- OFFER RESULTS -->
        <% if @offer_results %>
          <% if offer.id.in? @offer_results %>
              <%= render 'components/offer_card', offer: offer %>
          <% end %>
        <% end %>

      <% end %>
    <% else %>
      <% @offers.each do |offer| %>
        <%= render 'components/offer_card', offer: offer %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/offers/show.html.erb
<!-- Offer Card -->
<div class='container-booking' style="display: flex; justify-content: center; margin-top: 60px; align-items: baseline">
  <div class='item-booking' style="margin-right: 25px;">
    <%= render 'components/offer_card', offer: @offer %>
  </div>
  <!-- Booking -->
  <div class='item-booking' style='text-align: center;'>
    <%= simple_form_for [@offer, @booking] do |f| %>
    <%= f.input :booking_date, as: :string, required: true, input_html: {class: "datepicker"} %>
    <%= f.submit class: 'button button-primary' %>
    <% end %>
  </div>
</div>

  <!-- Reviews -->
<div class="reviews mt-5">
  <h2 class="text-center font-weight-bold mb-4">Reviews</h2>
  <ul style="list-style-type: none">
    <% @offer.reviews.each do |review| %>
    <div class="mb-3 mx-auto rounded" style="background-color: #F3F3F3; border: 1px solid hsla(200, 20%, 20%, 0.1); box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05); padding: 20px; width: 800px; position: relative;">
      <li class="mb-2"> <strong> <%= review.title %> </strong></li>
      <li> <%= review.content %> </li>
      <li style="position: absolute; top: 20px; right: 20px;"> ⭐️ <strong><%= review.rating %> </strong></li>
    </div>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<!-- BANNER -->
<div id="banner">
  <h1>Need technical help?</h1>
  <h4>Find someone who can actually help <br> you and book an appointment</h4>
  <a href="/offers" class="button button-highlight text-xxl">
    See offers
  </a>
</div>

<!-- RECENT OFFERS -->
<div id="recent">
  <h3>Recent Offers:</h3>
  <div id="con">
    <% Offer.all.sample(3).each do |offer| %>
      <%= render "components/offer_card", offer: offer %>
    <% end %>
  </div>
</div>

<!-- REVIEW -->
<div id="review">
  <h3>“I finally found my perfect teaching assistant”</h3>
  <h6>Batch 605 participant - Le Wagon 2021</h6>
</div>

app/views/pages/team.html.erb
<div class="team flex flex-col items-center">

</div>